version: "3.3"
services:  
  containerload:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
                # Ambiente
                - AMBIENTE=DEV
    volumes:
                - './app:/app'
    ports:
                - "5000:5000"
